development:
  adapter: postgresql
  database: heroku-testing_development
  pool: 5
  timeout: 5000
staging:
  adapter: postgresql
  database: heroku-testing_staging
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: heroku-testing_production
  pool: 5
  timeout: 5000